'use client'
import { useAppDispatch, useAppSelector } from '@/store'
import {
  addOne,
  initCounterState,
  resetCount,
  substractOne
} from '@/store/counter/counterSlice'
import { FC, useEffect } from 'react'

interface CartCounterProps {
  value?: number
}

// Generated by https://quicktype.io

export interface CounterResponse {
  count: number
  method: string
}

const getApiCounter = async (): Promise<CounterResponse> => {
  const data = await fetch('/api/counter').then(response => response.json())
  console.log({ data })
  return data
}

export const CartCounter: FC<CartCounterProps> = ({ value = 0 }) => {
  const count = useAppSelector(state => state.counter.count)
  const dispatch = useAppDispatch()

  useEffect(() => {
    getApiCounter()
      .then(({ count }) => {
        dispatch(initCounterState(count))
      })
      .catch(error => console.log({ error }))
  }, [dispatch])

  // useEffect(() => {
  //   dispatch(initCounterState(value))
  // }, [dispatch, value])

  return (
    <>
      <span className="text-9xl">{count}</span>
      <div className="flex gap-2">
        <button
          className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px]"
          onClick={() => dispatch(substractOne())}
        >
          -1
        </button>
        <button
          className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px]"
          onClick={() => dispatch(addOne())}
        >
          +1
        </button>
      </div>
    </>
  )
}
